In [1]:
import numpy as  np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [2]:
b=np.array([[1,2,3,],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a=np.zeros(2)
a

array([0., 0.])

In [4]:
a=np.array([1,2,3,4])
a.ndim

1

In [5]:
print(a[0])
print(b[0,1])
print(a[1:3])

1
2
[2 3]


In [7]:
d=np.arange(10)
d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(d.dtype.name)
print(d.size)
print(type(d))
a=np.arange(5)
b=np.arange(0,10,2)
print(a-b)
print(a*b)
print(b**2)
print(a.max())
print(a.min())
print(a.sum())


int32
10
<class 'numpy.ndarray'>
[ 0 -1 -2 -3 -4]
[ 0  2  8 18 32]
[ 0  4 16 36 64]
4
0
10


In [10]:
c=np.linspace(0,10,4)
c

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [17]:
a=np.array([[3,7,3,4],[1,4,2,2],[7,2,1,9]])
a.resize((2,6))
a

array([[3, 7, 3, 4, 1, 4],
       [2, 2, 7, 2, 1, 9]])

In [19]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a=np.array([1,5,3,4,7,3,5])
np.sort(a)

array([1, 3, 3, 4, 5, 5, 7])

In [24]:
print(a.shape)
print(a.mean())
print(a.std())
arr=np.array([-2,2,6,10,14,18,22])
print(arr[::-1])
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(7,)
4.0
1.7728105208558367
[22 18 14 10  6  2 -2]
7
int32
4
